name: Commit Message Lint

on:
  push:
    branches:
      - main
      - dev
      - feature/**
  pull_request:

jobs:
  lint-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v5
